import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./_providers/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>SAMPH</title>
      </head>
      <body className={inter.className}>
        <AuthProvider>
          <div className="flex h-full flex-col">{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
